//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParameterForm.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circle", ReplyAction="*")]
        double Circle(int r, int g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CircleAsync(int r, int g);
        
        // CODEGEN: Generating message contract since element name inputText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/abc", ReplyAction="*")]
        ParameterForm.ServiceReference4.abcResponse abc(ParameterForm.ServiceReference4.abcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/abc", ReplyAction="*")]
        System.Threading.Tasks.Task<ParameterForm.ServiceReference4.abcResponse> abcAsync(ParameterForm.ServiceReference4.abcRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class abcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="abc", Namespace="http://tempuri.org/", Order=0)]
        public ParameterForm.ServiceReference4.abcRequestBody Body;
        
        public abcRequest() {
        }
        
        public abcRequest(ParameterForm.ServiceReference4.abcRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class abcRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputText;
        
        public abcRequestBody() {
        }
        
        public abcRequestBody(string inputText) {
            this.inputText = inputText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class abcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="abcResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParameterForm.ServiceReference4.abcResponseBody Body;
        
        public abcResponse() {
        }
        
        public abcResponse(ParameterForm.ServiceReference4.abcResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class abcResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string abcResult;
        
        public abcResponseBody() {
        }
        
        public abcResponseBody(string abcResult) {
            this.abcResult = abcResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ParameterForm.ServiceReference4.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ParameterForm.ServiceReference4.WebService1Soap>, ParameterForm.ServiceReference4.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Circle(int r, int g) {
            return base.Channel.Circle(r, g);
        }
        
        public System.Threading.Tasks.Task<double> CircleAsync(int r, int g) {
            return base.Channel.CircleAsync(r, g);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParameterForm.ServiceReference4.abcResponse ParameterForm.ServiceReference4.WebService1Soap.abc(ParameterForm.ServiceReference4.abcRequest request) {
            return base.Channel.abc(request);
        }
        
        public string abc(string inputText) {
            ParameterForm.ServiceReference4.abcRequest inValue = new ParameterForm.ServiceReference4.abcRequest();
            inValue.Body = new ParameterForm.ServiceReference4.abcRequestBody();
            inValue.Body.inputText = inputText;
            ParameterForm.ServiceReference4.abcResponse retVal = ((ParameterForm.ServiceReference4.WebService1Soap)(this)).abc(inValue);
            return retVal.Body.abcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParameterForm.ServiceReference4.abcResponse> ParameterForm.ServiceReference4.WebService1Soap.abcAsync(ParameterForm.ServiceReference4.abcRequest request) {
            return base.Channel.abcAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParameterForm.ServiceReference4.abcResponse> abcAsync(string inputText) {
            ParameterForm.ServiceReference4.abcRequest inValue = new ParameterForm.ServiceReference4.abcRequest();
            inValue.Body = new ParameterForm.ServiceReference4.abcRequestBody();
            inValue.Body.inputText = inputText;
            return ((ParameterForm.ServiceReference4.WebService1Soap)(this)).abcAsync(inValue);
        }
    }
}
