//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace home_page.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circle", ReplyAction="*")]
        double Circle(int r, int g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CircleAsync(int r, int g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cvolume", ReplyAction="*")]
        double Cvolume(int r, int g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cvolume", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CvolumeAsync(int r, int g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rectangle", ReplyAction="*")]
        double Rectangle(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rectangle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RectangleAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rvolume", ReplyAction="*")]
        double Rvolume(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rvolume", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RvolumeAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Square", ReplyAction="*")]
        double Square(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Square", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SquareAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Svolume", ReplyAction="*")]
        double Svolume(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Svolume", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SvolumeAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Triangle", ReplyAction="*")]
        double Triangle(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Triangle", ReplyAction="*")]
        System.Threading.Tasks.Task<double> TriangleAsync(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tvolume", ReplyAction="*")]
        double Tvolume(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tvolume", ReplyAction="*")]
        System.Threading.Tasks.Task<double> TvolumeAsync(int a, int b, int c);
        
        // CODEGEN: Generating message contract since element name inputText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/braile", ReplyAction="*")]
        home_page.ServiceReference1.braileResponse braile(home_page.ServiceReference1.braileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/braile", ReplyAction="*")]
        System.Threading.Tasks.Task<home_page.ServiceReference1.braileResponse> braileAsync(home_page.ServiceReference1.braileRequest request);
        
        // CODEGEN: Generating message contract since element name inputText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/braileC", ReplyAction="*")]
        home_page.ServiceReference1.braileCResponse braileC(home_page.ServiceReference1.braileCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/braileC", ReplyAction="*")]
        System.Threading.Tasks.Task<home_page.ServiceReference1.braileCResponse> braileCAsync(home_page.ServiceReference1.braileCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/braileV", ReplyAction="*")]
        double braileV(int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/braileV", ReplyAction="*")]
        System.Threading.Tasks.Task<double> braileVAsync(int c);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class braileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="braile", Namespace="http://tempuri.org/", Order=0)]
        public home_page.ServiceReference1.braileRequestBody Body;
        
        public braileRequest() {
        }
        
        public braileRequest(home_page.ServiceReference1.braileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class braileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputText;
        
        public braileRequestBody() {
        }
        
        public braileRequestBody(string inputText) {
            this.inputText = inputText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class braileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="braileResponse", Namespace="http://tempuri.org/", Order=0)]
        public home_page.ServiceReference1.braileResponseBody Body;
        
        public braileResponse() {
        }
        
        public braileResponse(home_page.ServiceReference1.braileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class braileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string braileResult;
        
        public braileResponseBody() {
        }
        
        public braileResponseBody(string braileResult) {
            this.braileResult = braileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class braileCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="braileC", Namespace="http://tempuri.org/", Order=0)]
        public home_page.ServiceReference1.braileCRequestBody Body;
        
        public braileCRequest() {
        }
        
        public braileCRequest(home_page.ServiceReference1.braileCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class braileCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputText;
        
        public braileCRequestBody() {
        }
        
        public braileCRequestBody(string inputText) {
            this.inputText = inputText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class braileCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="braileCResponse", Namespace="http://tempuri.org/", Order=0)]
        public home_page.ServiceReference1.braileCResponseBody Body;
        
        public braileCResponse() {
        }
        
        public braileCResponse(home_page.ServiceReference1.braileCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class braileCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int braileCResult;
        
        public braileCResponseBody() {
        }
        
        public braileCResponseBody(int braileCResult) {
            this.braileCResult = braileCResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : home_page.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<home_page.ServiceReference1.WebService1Soap>, home_page.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Circle(int r, int g) {
            return base.Channel.Circle(r, g);
        }
        
        public System.Threading.Tasks.Task<double> CircleAsync(int r, int g) {
            return base.Channel.CircleAsync(r, g);
        }
        
        public double Cvolume(int r, int g) {
            return base.Channel.Cvolume(r, g);
        }
        
        public System.Threading.Tasks.Task<double> CvolumeAsync(int r, int g) {
            return base.Channel.CvolumeAsync(r, g);
        }
        
        public double Rectangle(int x, int y) {
            return base.Channel.Rectangle(x, y);
        }
        
        public System.Threading.Tasks.Task<double> RectangleAsync(int x, int y) {
            return base.Channel.RectangleAsync(x, y);
        }
        
        public double Rvolume(int x, int y) {
            return base.Channel.Rvolume(x, y);
        }
        
        public System.Threading.Tasks.Task<double> RvolumeAsync(int x, int y) {
            return base.Channel.RvolumeAsync(x, y);
        }
        
        public double Square(int x) {
            return base.Channel.Square(x);
        }
        
        public System.Threading.Tasks.Task<double> SquareAsync(int x) {
            return base.Channel.SquareAsync(x);
        }
        
        public double Svolume(int x) {
            return base.Channel.Svolume(x);
        }
        
        public System.Threading.Tasks.Task<double> SvolumeAsync(int x) {
            return base.Channel.SvolumeAsync(x);
        }
        
        public double Triangle(int a, int b, int c) {
            return base.Channel.Triangle(a, b, c);
        }
        
        public System.Threading.Tasks.Task<double> TriangleAsync(int a, int b, int c) {
            return base.Channel.TriangleAsync(a, b, c);
        }
        
        public double Tvolume(int a, int b, int c) {
            return base.Channel.Tvolume(a, b, c);
        }
        
        public System.Threading.Tasks.Task<double> TvolumeAsync(int a, int b, int c) {
            return base.Channel.TvolumeAsync(a, b, c);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        home_page.ServiceReference1.braileResponse home_page.ServiceReference1.WebService1Soap.braile(home_page.ServiceReference1.braileRequest request) {
            return base.Channel.braile(request);
        }
        
        public string braile(string inputText) {
            home_page.ServiceReference1.braileRequest inValue = new home_page.ServiceReference1.braileRequest();
            inValue.Body = new home_page.ServiceReference1.braileRequestBody();
            inValue.Body.inputText = inputText;
            home_page.ServiceReference1.braileResponse retVal = ((home_page.ServiceReference1.WebService1Soap)(this)).braile(inValue);
            return retVal.Body.braileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<home_page.ServiceReference1.braileResponse> home_page.ServiceReference1.WebService1Soap.braileAsync(home_page.ServiceReference1.braileRequest request) {
            return base.Channel.braileAsync(request);
        }
        
        public System.Threading.Tasks.Task<home_page.ServiceReference1.braileResponse> braileAsync(string inputText) {
            home_page.ServiceReference1.braileRequest inValue = new home_page.ServiceReference1.braileRequest();
            inValue.Body = new home_page.ServiceReference1.braileRequestBody();
            inValue.Body.inputText = inputText;
            return ((home_page.ServiceReference1.WebService1Soap)(this)).braileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        home_page.ServiceReference1.braileCResponse home_page.ServiceReference1.WebService1Soap.braileC(home_page.ServiceReference1.braileCRequest request) {
            return base.Channel.braileC(request);
        }
        
        public int braileC(string inputText) {
            home_page.ServiceReference1.braileCRequest inValue = new home_page.ServiceReference1.braileCRequest();
            inValue.Body = new home_page.ServiceReference1.braileCRequestBody();
            inValue.Body.inputText = inputText;
            home_page.ServiceReference1.braileCResponse retVal = ((home_page.ServiceReference1.WebService1Soap)(this)).braileC(inValue);
            return retVal.Body.braileCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<home_page.ServiceReference1.braileCResponse> home_page.ServiceReference1.WebService1Soap.braileCAsync(home_page.ServiceReference1.braileCRequest request) {
            return base.Channel.braileCAsync(request);
        }
        
        public System.Threading.Tasks.Task<home_page.ServiceReference1.braileCResponse> braileCAsync(string inputText) {
            home_page.ServiceReference1.braileCRequest inValue = new home_page.ServiceReference1.braileCRequest();
            inValue.Body = new home_page.ServiceReference1.braileCRequestBody();
            inValue.Body.inputText = inputText;
            return ((home_page.ServiceReference1.WebService1Soap)(this)).braileCAsync(inValue);
        }
        
        public double braileV(int c) {
            return base.Channel.braileV(c);
        }
        
        public System.Threading.Tasks.Task<double> braileVAsync(int c) {
            return base.Channel.braileVAsync(c);
        }
    }
}
